[project]
name = "appstream-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "logfmter>=0.0.10",
    "python-dotenv>=1.1.1",
]
